name: Job Without Depends

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Step A
        run: echo "run step A"

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Step B
        run: echo "run step B"