on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:  # 👈 Add this line

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: Echo current time
        run: echo "The current server time is $(date)"
